### ISSUE TITLE
Cellular signal gets lost with weak mobile signal or coverage

### ISSUE THREAD

**Issue by kapinta** [dreemurrs-embedded/Pine64-Arch#206] opened 2021-08-11 09:06 UTC
Hello all!
I have detected that when the mobile signal or coverage is low or weak on Pinephone, the cellular signal gets down and is not recovered again even if 4G signal is strong again. After this problem happens, cellular calls and mobile data are not enabled, and if you go to Settings Area, mobile settings disappear.
In earlier eg25-manager releases I usually executed systemctl restart eg25-manager to solve the problem, but actually it does not work. The only solution that I have found is to restart o.s.
This problem gets more usual with worst mobile coverage.
The eg25-manager release that I am using is 0.3.0+6+gf2593b6-1.
This problem could also be related to bug https://github.com/dreemurrs-embedded/Pine64-Arch/issues/185

For instance, I have collected journal log for eg25-manager. Today I just started mobile, got to work, checked its state and rebooted it as mobile signal and data were lost:

_ago 11 08:40:30 wombat audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=eg25-manager comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
ago 11 08:40:31 wombat eg25manager[3417]: Opening config file: /usr/share/eg25-manager/pine64,pinephone-1.2.toml
ago 11 08:40:31 wombat eg25manager[3417]: Starting modem...
ago 11 08:40:32 wombat eg25manager[3417]: Executed power-on/off sequence
ago 11 08:40:32 wombat dbus-daemon[3415]: [system] Activating via systemd: service name='org.freedesktop.ModemManager1' unit='dbus-org.freedesktop.ModemManager1.service' requested by ':1.2' (uid=0 pid=3417 comm="/usr/bin/eg25manager ")
ago 11 08:40:32 wombat eg25manager[3417]: taking systemd sleep inhibitor
ago 11 08:40:32 wombat eg25manager[3417]: oFono vanished from D-Bus
ago 11 08:40:32 wombat eg25manager[3417]: inhibitor sleep fd is 20
ago 11 08:40:32 wombat eg25manager[3417]: ModemManager appeared on D-Bus
ago 11 08:40:42 wombat eg25manager[3417]: Response: [RDY]
ago 11 08:40:42 wombat eg25manager[3417]: taking systemd sleep inhibitor (blocking)
ago 11 08:40:42 wombat eg25manager[3417]: Response: [+CPIN: SIM PIN]
ago 11 08:40:42 wombat eg25manager[3417]: inhibitor block fd is 21
ago 11 08:40:42 wombat eg25manager[3417]: Response: [+CFUN: 1]
ago 11 08:40:51 wombat eg25manager[3417]: ModemManager object `/org/freedesktop/ModemManager1/Modem/0' added
ago 11 08:40:51 wombat eg25manager[3417]: ModemManager interface `org.freedesktop.ModemManager1.Modem' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 08:40:51 wombat eg25manager[3417]: Adding new modem `/org/freedesktop/ModemManager1/Modem/0'
ago 11 08:40:51 wombat eg25manager[3417]: Executed soft wake sequence
ago 11 08:40:51 wombat eg25manager[3417]: Sending command: AT+QGMR
ago 11 08:40:51 wombat eg25manager[3417]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Voice' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 08:40:51 wombat eg25manager[3417]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Firmware' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 08:40:51 wombat eg25manager[3417]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Simple' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 08:40:51 wombat eg25manager[3417]: Response: [EG25GGBR07A08M2G_01.002.01.002
ago 11 08:40:51 wombat eg25manager[3417]: Executed soft wake sequence
ago 11 08:40:51 wombat eg25manager[3417]: Sending command: AT+QDAI?
ago 11 08:40:52 wombat eg25manager[3417]: Response: [+QDAI: 1,1,0,1,0,0,1,1
ago 11 08:40:52 wombat eg25manager[3417]: Executed soft wake sequence
ago 11 08:40:52 wombat eg25manager[3417]: Sending command: AT+QCFG="risignaltype"
ago 11 08:40:52 wombat eg25manager[3417]: Response: [+QCFG: "risignaltype","physical"
ago 11 08:40:52 wombat eg25manager[3417]: Executed soft wake sequence
ago 11 08:40:52 wombat eg25manager[3417]: Sending command: AT+QCFG="ims"
ago 11 08:40:52 wombat eg25manager[3417]: Response: [+QCFG: "ims",1,0
ago 11 08:40:52 wombat eg25manager[3417]: Executed soft wake sequence
ago 11 08:40:52 wombat eg25manager[3417]: Sending command: AT+QCFG="apready"
ago 11 08:40:52 wombat eg25manager[3417]: Response: [+QCFG: "apready",1,0,500
ago 11 08:40:52 wombat eg25manager[3417]: Executed soft wake sequence
ago 11 08:40:52 wombat eg25manager[3417]: Sending command: AT+QURCCFG="urcport"
ago 11 08:40:52 wombat eg25manager[3417]: Response: [+QURCCFG: "urcport","all"
ago 11 08:40:52 wombat eg25manager[3417]: Executed soft wake sequence
ago 11 08:40:52 wombat eg25manager[3417]: Sending command: AT+QGPS=1
ago 11 08:40:52 wombat eg25manager[3417]: Response: [OK]
ago 11 08:40:52 wombat eg25manager[3417]: Executed soft wake sequence
ago 11 08:40:52 wombat eg25manager[3417]: Sending command: AT+QSCLK=1
ago 11 08:40:52 wombat eg25manager[3417]: Response: [OK]
ago 11 08:40:52 wombat eg25manager[3417]: Executed soft sleep sequence
ago 11 08:42:43 wombat eg25manager[3417]: Modem is up for 120 seconds and fully ready
ago 11 08:42:43 wombat eg25manager[3417]: dropping systemd sleep block inhibitor
ago 11 08:53:52 wombat eg25manager[3417]: Response: [+CPIN: READY
ago 11 08:53:52 wombat eg25manager[3417]: Response: [+QIND: SMS DONE]
ago 11 08:53:53 wombat eg25manager[3417]: Response: [+QIND: PB DONE]
ago 11 08:53:54 wombat eg25manager[3417]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Modem3gpp' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 08:53:54 wombat eg25manager[3417]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Modem3gpp.Ussd' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 08:53:54 wombat eg25manager[3417]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Location' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 08:53:55 wombat eg25manager[3417]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Messaging' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 08:53:55 wombat eg25manager[3417]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Time' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 08:53:55 wombat eg25manager[3417]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Signal' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 08:53:55 wombat eg25manager[3417]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Voice' removed on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 08:53:55 wombat eg25manager[3417]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Voice' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 08:53:55 wombat eg25manager[3417]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Firmware' removed on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 08:53:55 wombat eg25manager[3417]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Firmware' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 09:03:25 wombat eg25manager[3417]: ModemManager object `/org/freedesktop/ModemManager1/Modem/0' removed
ago 11 09:03:25 wombat eg25manager[3417]: Lost modem, resetting...
ago 11 09:03:25 wombat eg25manager[3417]: Couldn't unbind modem: wrote -1/3 bytes
ago 11 09:03:25 wombat eg25manager[3417]: Couldn't bind modem: wrote -1/3 bytes
ago 11 09:03:35 wombat systemd-udevd[4629]: 2-1: /usr/lib/udev/rules.d/80-modem-eg25.rules:3 Failed to write ATTR{/sys/devices/platform/soc/1c1b000.usb/usb2/2-1/power/wakeup}, ignoring: No such file or directory
ago 11 09:34:51 wombat audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=eg25-manager comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
ago 11 09:34:51 wombat systemd[1]: eg25-manager.service: Deactivated successfully.
ago 11 09:35:08 wombat audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=eg25-manager comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
ago 11 09:35:08 wombat eg25manager[3415]: Opening config file: /usr/share/eg25-manager/pine64,pinephone-1.2.toml
ago 11 09:35:08 wombat eg25manager[3415]: Starting modem...
ago 11 09:35:10 wombat eg25manager[3415]: Executed power-on/off sequence
ago 11 09:35:10 wombat dbus-daemon[3406]: [system] Activating via systemd: service name='org.freedesktop.ModemManager1' unit='dbus-org.freedesktop.ModemManager1.service' requested by ':1.2' (uid=0 pid=3415 comm="/usr/bin/eg25manager ")
ago 11 09:35:10 wombat eg25manager[3415]: taking systemd sleep inhibitor
ago 11 09:35:10 wombat eg25manager[3415]: oFono vanished from D-Bus
ago 11 09:35:10 wombat eg25manager[3415]: inhibitor sleep fd is 20
ago 11 09:35:10 wombat eg25manager[3415]: ModemManager appeared on D-Bus
ago 11 09:35:30 wombat eg25manager[3415]: ModemManager object `/org/freedesktop/ModemManager1/Modem/0' added
ago 11 09:35:30 wombat eg25manager[3415]: ModemManager interface `org.freedesktop.ModemManager1.Modem' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 09:35:30 wombat eg25manager[3415]: Adding new modem `/org/freedesktop/ModemManager1/Modem/0'
ago 11 09:35:30 wombat eg25manager[3415]: Executed soft wake sequence
ago 11 09:35:30 wombat eg25manager[3415]: Sending command: AT+QGMR
ago 11 09:35:30 wombat eg25manager[3415]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Voice' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 09:35:30 wombat eg25manager[3415]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Firmware' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 09:35:30 wombat eg25manager[3415]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Simple' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 09:36:08 wombat eg25manager[3415]: [15B blob data]
ago 11 09:36:08 wombat eg25manager[3415]: Executed soft wake sequence
ago 11 09:36:08 wombat eg25manager[3415]: Sending command: AT+QDAI?
ago 11 09:36:09 wombat eg25manager[3415]: [14B blob data]
ago 11 09:36:09 wombat eg25manager[3415]: Executed soft wake sequence
ago 11 09:36:09 wombat eg25manager[3415]: Sending command: AT+QCFG="risignaltype"
ago 11 09:36:10 wombat eg25manager[3415]: [14B blob data]
ago 11 09:36:10 wombat eg25manager[3415]: Executed soft wake sequence
ago 11 09:36:10 wombat eg25manager[3415]: Sending command: AT+QCFG="ims"
ago 11 09:36:11 wombat eg25manager[3415]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Modem3gpp' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 09:36:11 wombat eg25manager[3415]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Modem3gpp.Ussd' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 09:36:11 wombat eg25manager[3415]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Location' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 09:36:11 wombat eg25manager[3415]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Messaging' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 09:36:11 wombat eg25manager[3415]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Time' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 09:36:11 wombat eg25manager[3415]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Signal' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 09:36:11 wombat eg25manager[3415]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Voice' removed on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 09:36:11 wombat eg25manager[3415]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Voice' found on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 09:36:11 wombat eg25manager[3415]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Firmware' removed on object `/org/freedesktop/ModemManager1/Modem/0'
ago 11 09:36:12 wombat eg25manager[3415]: ModemManager interface `org.freedesktop.ModemManager1.Modem.Firmware' found on object `/org/freedesktop/ModemManager1/Modem/0'__

Could you please help to solve this issue?
Thanks in advance!

**Comment by Danct12** [comment] 2021-08-14 14:11
Duplicate of #185

**Closed by Danct12** 2021-08-14 14:11 UTC
