### ISSUE TITLE
Pinephone pro extremely fast media playback

### ISSUE THREAD

**Issue by caveman250** [dreemurrs-embedded/Pine64-Arch#423] opened 2022-07-05 23:44 UTC
- Device: PinePhone Pro
- Kernel Version : 5.18.4-1.danctnix
- UI: Phosh

### Steps to reproduce
I am unsure of how to reproduce the issue,. but intermittently my pinephone pro will playback any type of media several times faster than it should be. Behavior can be seen across multiple apps including Firefox, Spot, Headlines, Amberol ect. I also have no idea how to fix the issue, it just goes away after a day or two. rebooting does not seem to make a difference.

### Expected behavior
Media plays back at the correct speed.

### Actual behavior
Media plays back very fast.

[journalctl.txt](https://github.com/dreemurrs-embedded/Pine64-Arch/files/9050282/journalctl.txt)

**Comment by caveman250** [comment] 2022-07-05 23:46
Just realized my journalctl contained multiple session sorry about that. The issue was occuring in the most recent session when i took that log.

**Comment by Danct12** [comment] 2022-07-06 01:35
Duplicate of #381

**Closed by Danct12** 2022-07-06 01:35 UTC
