### ISSUE TITLE
 Camera function is not available

### ISSUE THREAD

**Issue by jasper2007111** [dreemurrs-embedded/Pine64-Arch#642] opened 2024-06-08 23:22 UTC
**Device info (please complete the following information)**
- Device: PinePhone (Pro) 
- Version : Release Tag 20240326
- UI: Phosh

**Describe the bug**
 Camera function is not available. The Megapixels app does not respond after opening and will exit.

**Comment by Danct12** [comment] 2024-06-09 01:36
Duplicate of #256

**Closed by Danct12** 2024-06-09 01:36 UTC
Labels: bug
