### ISSUE TITLE
Possible logo change

### ISSUE THREAD

**Issue by mossymossmoss** [dreemurrs-embedded/Pine64-Arch#314] opened 2022-02-15 13:16 UTC
DanctNIX is a very cool project, and one that I have benefited from a lot as I have it installed on my PinePhone. I wanted to contribute something to the project, and I saw that it's current logo (pictured below) mostly just consists of Tux on an outline of a phone

![CurrentLogo](https://user-images.githubusercontent.com/56167669/154068472-fd60afc4-4366-4dce-b636-5f1834e83539.png)

I have made a couple mock-ups of what a new logo could be, one which is unique to the project and which may look slightly nicer on a phone's screen during boot-up. If anyone has any feedback, I can make adjustments or make a whole new design if that's what is wanted, but here are some different ideas of what a new logo could look like, along with variations that include a camera bar

![Danctnix1](https://user-images.githubusercontent.com/56167669/154069284-22a03231-c81d-4555-9f22-0e94543072f8.svg)
![Danctnix1Notch](https://user-images.githubusercontent.com/56167669/154069288-27b58254-1920-48a2-b9e2-e11a196a62f5.svg)
![Danctnix2](https://user-images.githubusercontent.com/56167669/154069292-6f67ad80-bd09-4ae7-a3aa-51b955a6618d.svg)
![Danctnix2Notch](https://user-images.githubusercontent.com/56167669/154069293-5557d358-ef3b-453d-a6e6-aaf514671109.svg)

 I am also more than happy to provide .svg files of the logos if anyone wants to edit them themselves in Inkscape

**Comment by Danct12** [comment] 2022-02-15 14:39
Duplicate of #235

**Closed by Danct12** 2022-02-15 14:39 UTC
