### ISSUE TITLE
PINETAB64 : Posh virtual keyboard not disabled automatically when physical keyboard attached

### ISSUE THREAD

**Issue by boyd8444** [dreemurrs-embedded/Pine64-Arch#71] opened 2020-10-13 00:54 UTC
When the physical keyboard is attached, the virtual keyboard is not disabled automatically and still pops-up when text input is required. Anyway to disable this behavior?

**Comment by Danct12** [comment] 2020-10-13 00:55
Duplicate of https://github.com/dreemurrs-embedded/Pine64-Arch/issues/53

**Closed by Danct12** 2020-10-13 00:55 UTC
Labels: duplicate
