### ISSUE TITLE
Some windows wider than the phone display

### ISSUE THREAD

**Issue by lindenr** [dreemurrs-embedded/Pine64-Arch#632] opened 2024-04-25 09:29 UTC
**Device info**
- Device: PinePhone
- Kernel Version : 6.7.7-1-danctnix
- UI: sxmo (wayland)

Apologies if I'm missing something obvious! I've only just recently starting using a pinephone.

**Describe the bug**
Firefox and gedit windows are too wide for the phone.

**To Reproduce**
Install firefox and gedit via `sudo pacman -S firefox gedit`.

Open firefox or gedit and observe that the right-hand side of all windows is out of the screen view area, and unscrollable.

On gedit you can keep typing and there are several characters which get typed out of visibility before word wrap kicks in.

Firefox's chrome is partially hidden as well as the displayed web pages, whereas gedit's chrome seems to be rendering correctly and just the textarea has a hidden part.

The terminal window `foot` displays correctly.

`swaymsg` seems to claim that all the windows I have, including gedit, firefox, and foot, are 360 pixels wide (which is as expected given the 2x scaling). I don't know how to ask firefox or gedit how wide they think their windows are, sorry.

**Expected behavior**
The windows are the same width as the phone screen, no hidden UI elements.

**Before submitting a bug report, please be sure that you have done the following:**
- [X] I have checked for updates (pacman -Syu) and installed the updates but the problem persisted.
- [X] I am **not** using Megi's multiboot image, which is unsupported by the developer.

**Comment by Danct12** [comment] 2024-04-26 12:01
Duplicate of #98

**Closed as completed by Danct12** 2024-04-26 12:01 UTC
Labels: bug
