### ISSUE TITLE
megapixels 1.4.3-1 won't open

### ISSUE THREAD

**Issue by fbmoose48** [dreemurrs-embedded/Pine64-Arch#269] opened 2022-01-07 05:10 UTC
- Device: PinePhone Pro
- Kernel Version : 5.16-rc8
- UI: Phosh

### Steps to reproduce
Launch megapixels either from gui or cli

### Expected behavior
megapixels opens

### Actual behavior
Megapixels doesn't open

### Logfiles and additional information
`/usr/share/megapixels/config/pine64,pinephone-pro.ini not found`
`Could not find any config file`

**Comment by Danct12** [comment] 2022-01-07 15:12
Duplicate of #256

**Closed by Danct12** 2022-01-07 15:12 UTC
